### ISSUE TITLE
EIGER serialization error

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#117]
$ dials.import ~/data/EIGER/Soleil/transthyretin/h5/200Hz_0.1dpf_1_master.h5 
$ dials.find_spots datablock.json nproc=8
$ dials.discover_better_experimental_model datablock.json strong.pickle 
The following parameters have been modified:

input {
  datablock = datablock.json
  reflections = strong.pickle
}

Selecting subset of 10000 reflections for analysis
Running DPS using 10000 reflections
Found 10 solutions with max unit cell 112.72 Angstroms.
Old beam centre: 115.04 mm, 124.28 mm
New beam centre: 114.97 mm, 124.26 mm
Shift: 0.07 mm, 0.02 mm
Traceback (most recent call last):
  File "/Users/rjgildea/software/cctbx/build/../modules/dials/command_line/discover_better_experimental_model.py", line 465, in <module>
    run(sys.argv[1:])
  File "/Users/rjgildea/software/cctbx/build/../modules/dials/command_line/discover_better_experimental_model.py", line 460, in run
    dump.datablock(datablock, params.output.datablock)
  File "/Users/rjgildea/Dropbox/cctbx/sources/cctbx_project/dxtbx/serialize/dump.py", line 115, in datablock
    dump.as_file(outfile, **kwargs)
  File "/Users/rjgildea/Dropbox/cctbx/sources/cctbx_project/dxtbx/datablock.py", line 941, in as_file
    return self.as_json(filename, **kwargs)
  File "/Users/rjgildea/Dropbox/cctbx/sources/cctbx_project/dxtbx/datablock.py", line 911, in as_json
    dictionary = [db.to_dict() for db in self._datablocks]
  File "/Users/rjgildea/Dropbox/cctbx/sources/cctbx_project/dxtbx/datablock.py", line 197, in to_dict
    template = abspath(iset.get_template())
  File "/Users/rjgildea/Dropbox/cctbx/sources/cctbx_project/dxtbx/imageset.py", line 1018, in get_template
    return template_format_to_string(self.reader()._filenames.template())
AttributeError: 'list' object has no attribute 'template'

**Comment by rjgildea** [comment]
Similar (although slightly different) error now from xia2:

Traceback (most recent call last):
  File "/Users/rjgildea/software/cctbx/build/../modules/xia2/command_line/xia2_main.py", line 283, in run
    xinfo = xia2_main()
  File "/Users/rjgildea/software/cctbx/build/../modules/xia2/command_line/xia2_main.py", line 214, in xia2_main
    sweep.serialize()
  File "/Users/rjgildea/software/cctbx/modules/xia2/Schema/XSweep.py", line 932, in serialize
    filename=os.path.join(indxr.get_working_directory(), "xia2.json"))
  File "/Users/rjgildea/software/cctbx/modules/xia2/Schema/Interfaces/Indexer.py", line 268, in as_json
    obj = self.to_dict()
  File "/Users/rjgildea/software/cctbx/modules/xia2/Schema/Interfaces/Indexer.py", line 237, in to_dict
    obj[a[0]] = [imageset_to_dict(imgset) for imgset in a[1]]
  File "/Users/rjgildea/Dropbox/cctbx/sources/cctbx_project/dxtbx/serialize/imageset.py", line 88, in imageset_to_dict
    return imagesweep_to_dict(imageset)
  File "/Users/rjgildea/Dropbox/cctbx/sources/cctbx_project/dxtbx/serialize/imageset.py", line 65, in imagesweep_to_dict
    ("template", filename_to_absolute(sweep.get_template())),
  File "/Users/rjgildea/Dropbox/cctbx/sources/cctbx_project/dxtbx/imageset.py", line 1018, in get_template
    return template_format_to_string(self.reader()._filenames.template())
AttributeError: 'SingleFileReader' object has no attribute '_filenames'

**Comment by jmp1985** [comment]
Fixed

**Comment by Anthchirp** [comment]
I think the fix for this broke approximately all the tests.
Most obvious one is dxtbx/tests/tst_imageset.py

**Comment by jmp1985** [comment]
OK, so now the tests pass!

**Comment by rjgildea** [comment]
I still get the second error, i.e.:

Traceback (most recent call last):
  File "/Users/rjgildea/software/cctbx/build/../modules/xia2/command_line/xia2_main.py", line 283, in run
    xinfo = xia2_main()
  File "/Users/rjgildea/software/cctbx/build/../modules/xia2/command_line/xia2_main.py", line 214, in xia2_main
    sweep.serialize()
  File "/Users/rjgildea/software/cctbx/modules/xia2/Schema/XSweep.py", line 931, in serialize
    filename=os.path.join(indxr.get_working_directory(), "xia2.json"))
  File "/Users/rjgildea/software/cctbx/modules/xia2/Schema/Interfaces/Indexer.py", line 268, in as_json
    obj = self.to_dict()
  File "/Users/rjgildea/software/cctbx/modules/xia2/Schema/Interfaces/Indexer.py", line 237, in to_dict
    obj[a[0]] = [imageset_to_dict(imgset) for imgset in a[1]]
  File "/Users/rjgildea/Dropbox/cctbx/sources/cctbx_project/dxtbx/serialize/imageset.py", line 88, in imageset_to_dict
    return imagesweep_to_dict(imageset)
  File "/Users/rjgildea/Dropbox/cctbx/sources/cctbx_project/dxtbx/serialize/imageset.py", line 65, in imagesweep_to_dict
    ("template", filename_to_absolute(sweep.get_template())),
  File "/Users/rjgildea/Dropbox/cctbx/sources/cctbx_project/dxtbx/imageset.py", line 1018, in get_template
    filenames = self.reader()._filenames

**Comment by jmp1985** [comment]
How to I run xia2 on this dataset? I've tried:

xia2 -dials image=/path/to/data/master.h5
xia2 -dials /path/to/data/

but both give errors.

**Comment by rjgildea** [comment]
This reproduces the error:

```
$ cat tst.py 
from dxtbx.datablock import DataBlockFactory
master_file = '/Users/rjgildea/data/EIGER/Soleil/transthyretin/h5/200Hz_0.1dpf_1_master.h5'
datablocks = DataBlockFactory.from_filenames([master_file])
imageset = datablocks[0].extract_sweeps()[0]
print imageset.reader()
from dxtbx.serialize.imageset import imagesweep_to_dict
d = imagesweep_to_dict(imageset)
```

```
$ dials.python tst.py 
<dxtbx.imageset.SingleFileReader object at 0x105899c90>
Traceback (most recent call last):
  File "tst.py", line 7, in <module>
    d = imagesweep_to_dict(imageset)
  File "/Users/rjgildea/Dropbox/cctbx/sources/cctbx_project/dxtbx/serialize/imageset.py", line 65, in imagesweep_to_dict
    ("template", filename_to_absolute(sweep.get_template())),
  File "/Users/rjgildea/Dropbox/cctbx/sources/cctbx_project/dxtbx/imageset.py", line 1018, in get_template
    filenames = self.reader()._filenames
AttributeError: 'SingleFileReader' object has no attribute '_filenames'
```

**Comment by jmp1985** [comment]
Third time lucky!
